# RULE CONFIGURATIONS

trailing_whitespace: 1
trailing_newline: 1
large_tuple: 3
line_length: 600

cyclomatic_complexity: 30

file_length: 1000

force_cast: warning

force_try:
severity: warning

function_body_length: 100

type_body_length: 300

type_name:
min_length: 2
max_length:
warning: 50
error: 60
excluded: iPhone

identifier_name:
min_length:
warning: 1

disabled_rules:
- fallthrough
- force_cast
- function_parameter_count
- multiple_closures_with_trailing_closure
- trailing_whitespace # enable it when maxEmptyLines configuration exists
- large_tuple
- valid_ibinspectable
- force_try
- identifier_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- R.generated.swift

